---
# Configuración de categorías para el sistema de gestión financiera

# Categorías de gastos con estructura jerárquica (categorías y subcategorías)
expense_categories:
  HOGAR:
    - Supermercado
    - Hipoteca / Alquiler
    - Electricidad
    - Gas / Calefacción
    - Agua / Alcantarillado / Basura
    - Teléfono
    - Cable / Satélite
    - Internet
    - Mobiliario / Electrodomésticos
    - Jardín / Patio
    - Mantenimiento / Mejoras
    - Otros

  TRANSPORTE:
    - Uber
    - Pagos del Automóvil
    - Seguro de Auto
    - Combustible
    - Transporte Público
    - Reparaciones / Mantenimiento
    - Registro / Licencia

  VIDA_DIARIA:
    - Comestibles
    - Comer Fuera
    - Ropa
    - Limpieza
    - Salón / Barbería
    - Artículos para Mascotas

  ENTRETENIMIENTO:
    - Games
    - Conciertos / Teatro
    - Deportes
    - Recreación al Aire Libre

  SALUD:
    - Seguro de Salud
    - Examenes
    - Visitas Médicas / Dentista
    - Medicamentos / Recetas
    - Veterinario
    - Seguro de Vida

  VACACIONES_DIAS_FESTIVOS:
    - Pasajes Aéreos
    - Alojamiento
    - Comida
    - Recuerdos
    - Hospedaje de Mascotas
    - Alquiler de Automóvil

# Categorías de ingresos (sin subcategorías)
income_categories:
  - Salario / Sueldos
  - Ingresos por Intereses
  - Dividendos
  - Reembolsos / Devoluciones
  - Negocio
  - Pensión
  - Varios