---
# Category configuration for the financial management system

# Expense categories with hierarchical structure (categories and subcategories)
expense_categories:
  HOME:
    - Supermarket
    - Mortgage / Rent
    - Electricity
    - Gas / Heating
    - Water / Sewage / Garbage
    - Phone
    - Cable / Satellite
    - Internet
    - Furniture / Appliances
    - Garden / Patio
    - Maintenance / Improvements
    - Other

  TRANSPORTATION:
    - Uber
    - Car Payments
    - Car Insurance
    - Fuel
    - Public Transport
    - Repairs / Maintenance
    - Registration / License

  DAILY-LIFE:
    - Groceries
    - Eating Out
    - Clothing
    - Cleaning
    - Salon / Barbershop
    - Pet Supplies

  ENTERTAINMENT:
    - Games
    - Concerts / Theater
    - Sports
    - Outdoor Recreation

  HEALTH:
    - Health Insurance
    - Exams
    - Medical / Dental Visits
    - Medications / Prescriptions
    - Veterinary
    - Life Insurance

  HOLIDAYS-VACATIONS:
    - Airfare
    - Accommodation
    - Food
    - Souvenirs
    - Pet Boarding
    - Car Rental

  FUTURE:
    - Savings
    - Investments
    - Home Ownership

# Income categories (no subcategories)
income_categories:
  - Salary / Wages
  - Interest Income
  - Dividends
  - Refunds / Returns
  - Business
  - Pension
  - Miscellaneous